#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipcalc
Version  : 0.2.5
Release  : 2
URL      : https://gitlab.com/ipcalc/ipcalc/-/archive/0.2.5/ipcalc-0.2.5.tar.gz
Source0  : https://gitlab.com/ipcalc/ipcalc/-/archive/0.2.5/ipcalc-0.2.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: ipcalc-bin = %{version}-%{release}
Requires: ipcalc-license = %{version}-%{release}
BuildRequires : libmaxminddb-dev
Patch1: 0001-Add-install-section.patch

%description
# Information about ipcalc
This is a modern tool to assist in network address calculations for IPv4 and IPv6.
It acts both as a tool to output human readable information about a network or address,
as well as a tool suitable to be used by scripts or other programs.

%package bin
Summary: bin components for the ipcalc package.
Group: Binaries
Requires: ipcalc-license = %{version}-%{release}

%description bin
bin components for the ipcalc package.


%package license
Summary: license components for the ipcalc package.
Group: Default

%description license
license components for the ipcalc package.


%prep
%setup -q -n ipcalc-0.2.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550781100
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1550781100
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ipcalc
cp COPYING %{buildroot}/usr/share/package-licenses/ipcalc/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ipcalc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ipcalc/COPYING
